### ISSUE TITLE
git flow init -d uses empty branch prefixes for everything

### ISSUE THREAD

**Issue by adamrodger** [petervanderdoes/gitflow-avh#393] opened 2018-11-06 20:15 UTC
The new feature that allows branch prefixes to be specified via switches to `git flow init` defaults everything to empty strings:

https://github.com/petervanderdoes/gitflow-avh/blob/develop/git-flow-init#L93-L98

Since this option takes precedence over the existing options then they always end up being empty:

https://github.com/petervanderdoes/gitflow-avh/blob/develop/git-flow-init#L309

Example output:

```bash
$ git flow init -d
Using default branch names.

How to name your supporting branch prefixes?
Feature branches? []
Bugfix branches? []
Release branches? []
Hotfix branches? []
Support branches? []
Version tag prefix? []
Hooks and filters directory? [/tmp/test/.git/hooks]
```

**Comment by 27Bslash6** [comment] 2019-01-25 01:17
Can we get this merged and a new release ASAP please, the latest release has broken our builds due to this changed behaviour.

**Comment by HoNooD** [comment] 2019-01-26 09:09
Oops, it has not been fixed in release 1.12.0.

**Comment by HoNooD** [comment] 2019-01-26 09:10
Oops, not fix in release 1.12.0.

**Comment by adamrodger** [comment] 2019-01-26 11:50
I think I'll just need to rebase onto the latest version. I can probably do that later today.

**Comment by MalcolmK** [comment] 2019-01-29 14:05
Having the same problem.

**Comment by nvaken** [comment] 2019-02-01 11:53
Same issue here, our auto updates process failed because of these default being gone.

**Comment by nmaves** [comment] 2019-02-11 21:00
I just ran into this issue when trying to teach a new guy on our team about git-flow :)

I just looked at that PR and it looks good.  Anything you need more from the community?

**Comment by cremor** [comment] 2019-02-28 12:15
Git for Windows 2.21.0 has been released two days ago and it contains git-flow v1.12.0. That means that this bug now affects a lot more users.

The bug also affects the manual `git flow init` (without the `-d` parameter). Output is the same as shown in the initial comment of this issue.

@petervanderdoes Any chance to get this fix in a bugfix release? Waiting another one or two years for the next feature release of git-flow wouldn't be a good way to handle this.

**Comment by petervanderdoes** [comment] 2019-02-28 14:10
Just released 1.12.1 which should take  care of the issue

**Comment by adamrodger** [comment] 2019-02-28 14:35
Wait, did you close my MR instead of merging it? Seems a bit harsh

**Comment by petervanderdoes** [comment] 2019-02-28 16:09
I also wrote this on @adamrodger 's github page, and he commented "For what it's worth, I also reviewed the merged changes and I still think my implementation is clearer and neater":

My apologies @adamrodger I saw an email when I got to work and quickly made some changes without checking if there were PR's or not.

I will add your name to the changelog.

I just checked your code and wanted to comment on my implementation compared to yours.

My thought process is that if you use a parameter you explicitly tell the software that the given name is the name you want. In your implementation it still checks if there is a setting in a configuration somewhere and that would take precedent over the parameter.

**Comment by bnaurich** [comment] 2019-04-19 15:14
Our shop has been a GIT FLOW shop for over 5 years - long time use - and this bug is driving us crazy. PLEASE FIX THIS - the git flow init -d has always provided the default prefixes - if very few newbies do not want the defaults as its always been -that is on them - but PLEASE GET THIS FIXED.  This problem is still in 2.21 as of April 19, 2019 (the latest version available).  If few want blank prefix defaults - then give them another default like -db.

**Comment by hylke94** [comment] 2019-05-21 18:31
Still not fixed in 1.12.2 AVH Edition!!

**Comment by adamrodger** [comment] 2019-05-23 09:20
@petervanderdoes - see the comment from @hylke94 above. This is why my MR used the precedence order that it did. The new precedence order causes the problem above.

**Comment by petervanderdoes** [comment] 2019-05-23 13:37
You can set a default prefix value global or system wide as well.

This means that if you set a global master branch prefix as foo and the repository is not initialized yet it will suggest the prefix to be foo for the master branch. That's the reason the precedence order you suggest won't work @adamrodger  

I can see the issue as described by @hylke94 Hopefully I can find some time today to address this issue and release a new version.

**Comment by petervanderdoes** [comment] 2019-05-23 14:20
Hopefully this is fixed with the [1.12.3](https://github.com/petervanderdoes/gitflow-avh/releases/tag/1.12.3) release

**Closed by petervanderdoes** 2019-05-23 14:20 UTC

**Comment by hylke94** [comment] 2019-05-23 15:17
I will try it tomorrow evening (if Manjaro sees the new release this time directly ;)). Tonight I'm busy.

**Comment by hylke94** [comment] 2019-05-24 18:41
Requested an update of this package on the [aur package repository](https://aur.archlinux.org/packages/gitflow-avh). Guess I need to wait a little longer...

**Comment by hylke94** [comment] 2019-05-27 17:05
Confirmed that it works! Even empty prefixes are reset correctly again :+1:

**Comment by fabalint** [comment] 2019-06-25 12:59
Hi all,
I am on windows, with a not really upgradeable git/flow.
For me this quick-init works, and is ^c^v-able well..
Hopefully we'll get a fixed version soon! (:
(in the repo, in a shell: )
```bash
git flow init -fd ;\
git config --worktree gitflow.branch.master "master" ;\
git config --worktree gitflow.branch.develop "develop" ;\
git config --worktree gitflow.prefix.hotfix "hotfix/" ;\
git config --worktree gitflow.prefix.feature "feature/" ;\
git config --worktree gitflow.prefix.bugfix "bugfix/" ;\
git config --worktree gitflow.prefix.release "release/" ;\
git config --worktree gitflow.prefix.support "support/"
```

**Comment by Nethanos** [comment] 2020-03-23 18:34
You just need to pull the master and develop branches on your local repo. Always works for me.
